// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60WrGahE6aROsEmahyybwrMYBfFm-C-4',
    appId: '1:897091512915:web:9c2452901fd32ccebdf4a6',
    messagingSenderId: '897091512915',
    projectId: 'greenbasket-68707',
    authDomain: 'greenbasket-68707.firebaseapp.com',
    storageBucket: 'greenbasket-68707.firebasestorage.app',
    measurementId: 'G-S64N3WMNHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtDv2aJnYv6Uzg-rqrSKZ1HGH941B7tpc',
    appId: '1:897091512915:android:e67cc31ee38aa273bdf4a6',
    messagingSenderId: '897091512915',
    projectId: 'greenbasket-68707',
    storageBucket: 'greenbasket-68707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KwJe9Wdj0dTbMSk9EBgCGrJaQwmD8QM',
    appId: '1:897091512915:ios:740155e36bcfb024bdf4a6',
    messagingSenderId: '897091512915',
    projectId: 'greenbasket-68707',
    storageBucket: 'greenbasket-68707.firebasestorage.app',
    iosBundleId: 'com.adil.greenBasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_KwJe9Wdj0dTbMSk9EBgCGrJaQwmD8QM',
    appId: '1:897091512915:ios:740155e36bcfb024bdf4a6',
    messagingSenderId: '897091512915',
    projectId: 'greenbasket-68707',
    storageBucket: 'greenbasket-68707.firebasestorage.app',
    iosBundleId: 'com.adil.greenBasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD60WrGahE6aROsEmahyybwrMYBfFm-C-4',
    appId: '1:897091512915:web:d46e9fa0ef078d7cbdf4a6',
    messagingSenderId: '897091512915',
    projectId: 'greenbasket-68707',
    authDomain: 'greenbasket-68707.firebaseapp.com',
    storageBucket: 'greenbasket-68707.firebasestorage.app',
    measurementId: 'G-K84GP0T1C4',
  );
}
